const fs = require('fs');
const path = require('path');

/**
 * Converts a JSON cookie array to the Netscape HTTP Cookie File format.
 * @param {Array} cookiesArray 
 * @returns {string}
 */
function jsonToNetscape(cookiesArray) {
  let output = '# Netscape HTTP Cookie File\n';
  output += '# This file was automatically generated by the bot from cookies.json or YT_COOKIES env var.\n';
  output += '# Do not edit this file directly.\n\n';

  let savedCount = 0;
  let skippedCount = 0;
  const skippedNames = [];
  const savedNames = [];

  for (const cookie of cookiesArray) {
    if (!cookie.domain || !cookie.name) continue;

    // Skip unstable/frequently rotated session cookies (TS and CC) to prevent session invalidation
    if (cookie.name.endsWith('TS') || cookie.name.endsWith('CC')) {
      skippedCount++;
      skippedNames.push(cookie.name);
      continue;
    }

    savedCount++;
    savedNames.push(cookie.name);

    const domain = cookie.domain;
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathVal = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
    const name = cookie.name;
    const value = cookie.value || '';

    output += `${domain}\t${flag}\t${pathVal}\t${secure}\t${expiry}\t${name}\t${value}\n`;
  }
  console.log(`ℹ️ [Cookies Helper] Cookies processed: Saved ${savedCount} (${savedNames.join(', ')}), Skipped ${skippedCount} (${skippedNames.join(', ')})`);
  return output;
}

/**
 * Loads YouTube cookies, generates cookies.txt, and configures yt-dlp.
 * @returns {Array|undefined} Parsed cookie array if found, otherwise undefined.
 */
function setupCookies() {
  let cookies = null;

  // 1. Try to load from environment variable YT_COOKIES
  if (process.env.YT_COOKIES) {
    let rawCookies = process.env.YT_COOKIES.trim();
    try {
      // Robust cleanup: if wrapped in outer quotes, strip them
      if (rawCookies.startsWith('"') && rawCookies.endsWith('"')) {
        rawCookies = rawCookies.substring(1, rawCookies.length - 1);
      } else if (rawCookies.startsWith("'") && rawCookies.endsWith("'")) {
        rawCookies = rawCookies.substring(1, rawCookies.length - 1);
      }
      
      // Unescape escaped double quotes (\") and newlines (\n) if present
      rawCookies = rawCookies.replace(/\\"/g, '"')
                             .replace(/\\n/g, '\n')
                             .replace(/\\\\/g, '\\');

      let parsed = JSON.parse(rawCookies);
      // If user accidentally pasted [[{...}]], flatten it
      if (Array.isArray(parsed) && Array.isArray(parsed[0])) {
        parsed = parsed.flat();
      }
      cookies = parsed;
      console.log('✅ [Cookies Helper] Loaded cookies from YT_COOKIES environment variable');
    } catch (err) {
      console.error('⚠️ [Cookies Helper] Failed to parse YT_COOKIES environment variable:', err.message);
    }
  }

  // 2. Try to load from local cookies.json file
  if (!cookies) {
    const cookiesJsonPath = path.join(process.cwd(), 'cookies.json');
    if (fs.existsSync(cookiesJsonPath)) {
      try {
        const content = fs.readFileSync(cookiesJsonPath, 'utf8');
        cookies = JSON.parse(content);
        console.log('✅ [Cookies Helper] Loaded cookies from cookies.json');
      } catch (err) {
        console.error('⚠️ [Cookies Helper] Failed to read or parse cookies.json:', err.message);
      }
    }
  }

  // Find the yt-dlp package bin directory
  const ytDlpBinDir = path.join(process.cwd(), 'bin');
  const confPath = path.join(ytDlpBinDir, 'yt-dlp.conf');

  // Build the base configuration content (always include extractor-args for playlists)
  let confContent = `# Generated by cookies.js\n`;
  confContent += `--extractor-args "youtubetab:skip=authcheck"\n`;
  confContent += `--force-ipv4\n`;


  if (cookies && Array.isArray(cookies) && cookies.length > 0) {
    try {
      // Write Netscape cookies.txt to project root
      const cookiesTxtPath = path.join(process.cwd(), 'cookies.txt');
      const netscapeContent = jsonToNetscape(cookies);
      fs.writeFileSync(cookiesTxtPath, netscapeContent, 'utf8');
      console.log('✅ [Cookies Helper] Generated cookies.txt in Netscape format');

      // Append cookies to the configuration content
      const normalizedCookiesPath = cookiesTxtPath.replace(/\\/g, '/');
      confContent += `--cookies "${normalizedCookiesPath}"\n`;

      // Configure yt-dlp portable configuration in its binary directory
      if (fs.existsSync(ytDlpBinDir)) {
        fs.writeFileSync(confPath, confContent, 'utf8');
        console.log(`✅ [Cookies Helper] Configured yt-dlp config at: ${confPath}`);
      } else {
        console.warn(`⚠️ [Cookies Helper] yt-dlp bin directory not found at: ${ytDlpBinDir}. yt-dlp will run without config file.`);
      }

      return cookies;
    } catch (err) {
      console.error('⚠️ [Cookies Helper] Failed to write cookies or configuration file:', err.message);
    }
  } else {
    console.log('ℹ️ [Cookies Helper] No cookies configured. Running in unauthenticated mode.');
    
    // Always write the base configuration even in unauthenticated mode
    if (fs.existsSync(ytDlpBinDir)) {
      fs.writeFileSync(confPath, confContent, 'utf8');
      console.log(`✅ [Cookies Helper] Configured base yt-dlp config at: ${confPath}`);
    }

    // Cleanup old cookies file if it exists
    const cookiesTxtPath = path.join(process.cwd(), 'cookies.txt');
    if (fs.existsSync(cookiesTxtPath)) {
      try {
        fs.unlinkSync(cookiesTxtPath);
        console.log('🧹 [Cookies Helper] Cleaned up stale cookies.txt');
      } catch (err) {}
    }
  }

  return undefined;
}

module.exports = { setupCookies };
