const fs = require('fs');
const path = require('path');

// ============================================================
// Cookies Health State — diakses dari index.js untuk alert admin
// ============================================================
const cookiesHealth = {
  status: 'unknown',   // 'ok' | 'expiring_soon' | 'expired' | 'missing' | 'unknown'
  expiredNames: [],
  expiringSoonNames: [],
  checkedAt: null,
};

/**
 * Memeriksa apakah cookies YouTube masih valid.
 * @param {Array} cookiesArray - Array cookie objects
 * @returns {{ ok: boolean, expired: string[], expiringSoon: string[] }}
 */
function checkCookiesExpiry(cookiesArray) {
  const now = Math.floor(Date.now() / 1000);
  const SOON_THRESHOLD_DAYS = 3; // Peringatan jika kurang dari 3 hari
  const SOON_THRESHOLD_SECS = SOON_THRESHOLD_DAYS * 24 * 60 * 60;

  // Cookie kritis yang harus valid agar YouTube tidak blokir
  const CRITICAL_COOKIES = ['__Secure-1PSID', 'SAPISID', 'SID', '__Secure-3PSID', 'HSID', 'SSID'];

  const expired = [];
  const expiringSoon = [];

  for (const cookie of cookiesArray) {
    if (!cookie.name || !cookie.expirationDate) continue;
    if (!CRITICAL_COOKIES.includes(cookie.name)) continue;

    const expiry = Math.round(cookie.expirationDate);
    if (expiry > 0 && expiry < now) {
      expired.push(cookie.name);
    } else if (expiry > 0 && expiry - now < SOON_THRESHOLD_SECS) {
      expiringSoon.push(cookie.name);
    }
  }

  const ok = expired.length === 0;
  console.log(`🍪 [Cookies Health] Status: ${ok ? 'OK' : 'EXPIRED'} | Expired: [${expired.join(', ') || 'none'}] | Expiring soon: [${expiringSoon.join(', ') || 'none'}]`);
  return { ok, expired, expiringSoon };
}

/**
 * Kembalikan status kesehatan cookies yang terakhir dicek.
 * @returns {typeof cookiesHealth}
 */
function getCookiesHealth() {
  return cookiesHealth;
}

/**
 * Converts a raw HTTP Cookie Header string (key=value; key2=value2) to Netscape HTTP Cookie format.
 * @param {string} headerString 
 * @returns {string}
 */
function cookieHeaderToNetscape(headerString) {
  let output = '# Netscape HTTP Cookie File\n';
  output += '# Auto-converted from HTTP Cookie Header string\n\n';

  const pairs = headerString.split(';');
  let count = 0;
  for (const pair of pairs) {
    const trimmed = pair.trim();
    if (!trimmed) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const name = trimmed.substring(0, eqIdx).trim();
    const value = trimmed.substring(eqIdx + 1).trim();
    if (!name) continue;

    output += `.youtube.com\tTRUE\t/\tTRUE\t0\t${name}\t${value}\n`;
    count++;
  }
  console.log(`🍪 [Cookies Helper] Converted ${count} cookies from HTTP Header format to Netscape format.`);
  return output;
}

/**
 * Converts a JSON cookie array to the Netscape HTTP Cookie File format.
 * @param {Array} cookiesArray 
 * @returns {string}
 */
function jsonToNetscape(cookiesArray) {
  let output = '# Netscape HTTP Cookie File\n';
  output += '# This file was automatically generated by the bot from cookies.json or YT_COOKIES env var.\n';
  output += '# Do not edit this file directly.\n\n';

  let savedCount = 0;
  let skippedCount = 0;
  const skippedNames = [];
  const savedNames = [];

  for (const cookie of cookiesArray) {
    if (!cookie.domain || !cookie.name) continue;

    savedCount++;
    savedNames.push(cookie.name);

    const domain = cookie.domain;
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathVal = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
    const name = cookie.name;
    const value = cookie.value || '';

    output += `${domain}\t${flag}\t${pathVal}\t${secure}\t${expiry}\t${name}\t${value}\n`;
  }
  console.log(`ℹ️ [Cookies Helper] Cookies processed: Saved ${savedCount} (${savedNames.join(', ')})`);
  return output;
}

/**
 * Loads YouTube cookies, generates cookies.txt, and configures yt-dlp.
 * @returns {Array|undefined} Parsed cookie array if found, otherwise undefined.
 */
function setupCookies() {
  let cookies = null;

  // 1. Try to load from YOUTUBE_COOKIES (Netscape format - highest priority)
  if (process.env.YOUTUBE_COOKIES) {
    console.log('🍪 [Cookies Helper] Found YOUTUBE_COOKIES env variable (Netscape format)');
    try {
      const cookiesTxtPath = path.join(process.cwd(), 'cookies.txt');
      let netscapeContent = process.env.YOUTUBE_COOKIES.trim();
      // Strip surrounding quotes if any
      if ((netscapeContent.startsWith('"') && netscapeContent.endsWith('"')) ||
          (netscapeContent.startsWith("'") && netscapeContent.endsWith("'"))) {
        netscapeContent = netscapeContent.slice(1, -1);
      }

      // Auto-detect format: jika bentuknya header string (mengandung '=' dan ';', tanpa '#' atau '[')
      if (netscapeContent.includes(';') && netscapeContent.includes('=') && !netscapeContent.startsWith('#') && !netscapeContent.startsWith('[')) {
        console.log('🍪 [Cookies Helper] Detected HTTP Cookie Header format string. Auto-converting to Netscape format...');
        netscapeContent = cookieHeaderToNetscape(netscapeContent);
      } else {
        // Fix: Railway UI often converts tab characters to spaces when pasting.
        // Normalize each non-comment line so fields are separated by a single tab.
        netscapeContent = netscapeContent.split('\n').map(line => {
          const trimmed = line.trim();
          if (trimmed.startsWith('#') || trimmed === '') return line;
          // Split on actual tab OR 2+ spaces (Railway artifact), rejoin with tab
          return trimmed.split(/\t| {2,}/).join('\t');
        }).join('\n');
      }

      fs.writeFileSync(cookiesTxtPath, netscapeContent, 'utf8');

      // Debug: show first data line to verify tab format
      const firstDataLine = netscapeContent.split('\n').find(l => l.trim() && !l.startsWith('#'));
      if (firstDataLine) {
        const cols = firstDataLine.split('\t');
        console.log(`✅ [Cookies Helper] Written YOUTUBE_COOKIES to cookies.txt (${cols.length} columns in first line, name=${cols[5] || '?'}`);
      } else {
        console.log('✅ [Cookies Helper] Written YOUTUBE_COOKIES to cookies.txt');
      }

      // Configure yt-dlp conf
      const ytDlpBinDir = path.join(process.cwd(), 'bin');
      const confPath = path.join(ytDlpBinDir, 'yt-dlp.conf');
      let confContent = `# Generated by cookies.js\n`;
      confContent += `--extractor-args "youtubetab:skip=authcheck"\n`;
      const normalizedCookiesPath = cookiesTxtPath.replace(/\\/g, '/');
      confContent += `--cookies "${normalizedCookiesPath}"\n`;
      if (fs.existsSync(ytDlpBinDir)) {
        fs.writeFileSync(confPath, confContent, 'utf8');
        console.log(`✅ [Cookies Helper] Configured yt-dlp config at: ${confPath}`);
      }

      // Return dummy array so caller knows cookies are loaded
      return [{ name: 'YOUTUBE_COOKIES', value: 'netscape' }];
    } catch (err) {
      console.error('⚠️ [Cookies Helper] Failed to write YOUTUBE_COOKIES:', err.message);
    }
  }

  // 2. Try to load from environment variable YT_COOKIES (JSON format)
  if (process.env.YT_COOKIES) {
    console.log(`🔍 [Cookies Helper] YT_COOKIES raw length: ${process.env.YT_COOKIES.length}`);
    console.log(`🔍 [Cookies Helper] YT_COOKIES raw start: "${process.env.YT_COOKIES.substring(0, 60)}"`);
    let rawCookies = process.env.YT_COOKIES.trim();
    try {
      // Robust recursive cleanup: strip outer quotes and YT_COOKIES= prefix in any order
      let cleaned = false;
      do {
        cleaned = false;
        rawCookies = rawCookies.trim();
        if (rawCookies.startsWith('"') && rawCookies.endsWith('"')) {
          rawCookies = rawCookies.substring(1, rawCookies.length - 1);
          cleaned = true;
        } else if (rawCookies.startsWith("'") && rawCookies.endsWith("'")) {
          rawCookies = rawCookies.substring(1, rawCookies.length - 1);
          cleaned = true;
        } else if (rawCookies.startsWith('YT_COOKIES=')) {
          rawCookies = rawCookies.substring('YT_COOKIES='.length);
          cleaned = true;
        }
      } while (cleaned);
      
      // Unescape escaped double quotes (\") and newlines (\n) if present
      rawCookies = rawCookies.replace(/\\"/g, '"')
                             .replace(/\\n/g, '\n')
                             .replace(/\\\\/g, '\\');

      let parsed = JSON.parse(rawCookies);
      // If user accidentally pasted [[{...}]], flatten it
      if (Array.isArray(parsed) && Array.isArray(parsed[0])) {
        parsed = parsed.flat();
      }
      cookies = parsed;
      console.log('✅ [Cookies Helper] Loaded cookies from YT_COOKIES environment variable');
    } catch (err) {
      console.error('⚠️ [Cookies Helper] Failed to parse YT_COOKIES environment variable:', err.message);
    }
  }

  // 2. Try to load from local cookies.json file
  if (!cookies) {
    const cookiesJsonPath = path.join(process.cwd(), 'cookies.json');
    if (fs.existsSync(cookiesJsonPath)) {
      try {
        const content = fs.readFileSync(cookiesJsonPath, 'utf8');
        cookies = JSON.parse(content);
        console.log('✅ [Cookies Helper] Loaded cookies from cookies.json');
      } catch (err) {
        console.error('⚠️ [Cookies Helper] Failed to read or parse cookies.json:', err.message);
      }
    }
  }

  // Find the yt-dlp package bin directory
  const ytDlpBinDir = path.join(process.cwd(), 'bin');
  const confPath = path.join(ytDlpBinDir, 'yt-dlp.conf');

  // Build the base configuration content (always include extractor-args for playlists)
  let confContent = `# Generated by cookies.js\n`;
  confContent += `--extractor-args "youtubetab:skip=authcheck"\n`;


  if (cookies && Array.isArray(cookies) && cookies.length > 0) {
    try {
      // Write Netscape cookies.txt to project root
      const cookiesTxtPath = path.join(process.cwd(), 'cookies.txt');
      const netscapeContent = jsonToNetscape(cookies);
      fs.writeFileSync(cookiesTxtPath, netscapeContent, 'utf8');
      console.log('✅ [Cookies Helper] Generated cookies.txt in Netscape format');

      // === Cek kesehatan / expiry cookies ===
      const health = checkCookiesExpiry(cookies);
      cookiesHealth.checkedAt = new Date().toISOString();
      cookiesHealth.expiredNames = health.expired;
      cookiesHealth.expiringSoonNames = health.expiringSoon;
      if (!health.ok) {
        cookiesHealth.status = 'expired';
        console.error(`🚨 [Cookies Health] Ada ${health.expired.length} cookies KRITIS yang sudah EXPIRED: [${health.expired.join(', ')}]. Bot mungkin tidak bisa putar lagu dari YouTube!`);
      } else if (health.expiringSoon.length > 0) {
        cookiesHealth.status = 'expiring_soon';
        console.warn(`⚠️ [Cookies Health] ${health.expiringSoon.length} cookies akan expire dalam 3 hari: [${health.expiringSoon.join(', ')}]. Segera update cookies!`);
      } else {
        cookiesHealth.status = 'ok';
      }

      // Append cookies to the configuration content
      const normalizedCookiesPath = cookiesTxtPath.replace(/\\/g, '/');
      confContent += `--cookies "${normalizedCookiesPath}"\n`;

      // Configure yt-dlp portable configuration in its binary directory
      if (fs.existsSync(ytDlpBinDir)) {
        fs.writeFileSync(confPath, confContent, 'utf8');
        console.log(`✅ [Cookies Helper] Configured yt-dlp config at: ${confPath}`);
      } else {
        console.warn(`⚠️ [Cookies Helper] yt-dlp bin directory not found at: ${ytDlpBinDir}. yt-dlp will run without config file.`);
      }

      return cookies;
    } catch (err) {
      console.error('⚠️ [Cookies Helper] Failed to write cookies or configuration file:', err.message);
    }
  } else {
    console.log('ℹ️ [Cookies Helper] No cookies configured. Running in unauthenticated mode.');
    cookiesHealth.status = 'missing';
    cookiesHealth.checkedAt = new Date().toISOString();
    
    // Always write the base configuration even in unauthenticated mode
    if (fs.existsSync(ytDlpBinDir)) {
      fs.writeFileSync(confPath, confContent, 'utf8');
      console.log(`✅ [Cookies Helper] Configured base yt-dlp config at: ${confPath}`);
    }

    // Cleanup old cookies file if it exists
    const cookiesTxtPath = path.join(process.cwd(), 'cookies.txt');
    if (fs.existsSync(cookiesTxtPath)) {
      try {
        fs.unlinkSync(cookiesTxtPath);
        console.log('🧹 [Cookies Helper] Cleaned up stale cookies.txt');
      } catch (err) {}
    }
  }

  return undefined;
}

module.exports = { setupCookies, getCookiesHealth };
