const fs = require('fs');
const path = require('path');

// ============================================================
// Cookies Health State — diakses dari index.js untuk alert admin
// ============================================================
const cookiesHealth = {
  status: 'unknown',   // 'ok' | 'expiring_soon' | 'expired' | 'missing' | 'unknown'
  expiredNames: [],
  expiringSoonNames: [],
  checkedAt: null,
};

/**
 * Memeriksa apakah cookies YouTube masih valid.
 * @param {Array} cookiesArray - Array cookie objects
 * @returns {{ ok: boolean, expired: string[], expiringSoon: string[] }}
 */
function checkCookiesExpiry(cookiesArray) {
  const now = Math.floor(Date.now() / 1000);
  const SOON_THRESHOLD_DAYS = 3; // Peringatan jika kurang dari 3 hari
  const SOON_THRESHOLD_SECS = SOON_THRESHOLD_DAYS * 24 * 60 * 60;

  // Cookie kritis yang harus valid agar YouTube tidak blokir
  const CRITICAL_COOKIES = ['__Secure-1PSID', 'SAPISID', 'SID', '__Secure-3PSID', 'HSID', 'SSID'];

  const expired = [];
  const expiringSoon = [];

  for (const cookie of cookiesArray) {
    if (!cookie.name || !cookie.expirationDate) continue;
    if (!CRITICAL_COOKIES.includes(cookie.name)) continue;

    const expiry = Math.round(cookie.expirationDate);
    if (expiry > 0 && expiry < now) {
      expired.push(cookie.name);
    } else if (expiry > 0 && expiry - now < SOON_THRESHOLD_SECS) {
      expiringSoon.push(cookie.name);
    }
  }

  const ok = expired.length === 0;
  console.log(`🍪 [Cookies Health] Status: ${ok ? 'OK' : 'EXPIRED'} | Expired: [${expired.join(', ') || 'none'}] | Expiring soon: [${expiringSoon.join(', ') || 'none'}]`);
  return { ok, expired, expiringSoon };
}

/**
 * Kembalikan status kesehatan cookies yang terakhir dicek.
 * @returns {typeof cookiesHealth}
 */
function getCookiesHealth() {
  return cookiesHealth;
}

/**
 * Converts a raw HTTP Cookie Header string (key=value; key2=value2) to Netscape HTTP Cookie format.
 * @param {string} headerString 
 * @returns {string}
 */
function cookieHeaderToNetscape(headerString) {
  let output = '# Netscape HTTP Cookie File\n';
  output += '# Auto-converted from HTTP Cookie Header string\n\n';

  const pairs = headerString.split(';');
  let count = 0;
  for (const pair of pairs) {
    const trimmed = pair.trim();
    if (!trimmed) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const name = trimmed.substring(0, eqIdx).trim();
    const value = trimmed.substring(eqIdx + 1).trim();
    if (!name) continue;

    output += `.youtube.com\tTRUE\t/\tTRUE\t0\t${name}\t${value}\n`;
    count++;
  }
  console.log(`🍪 [Cookies Helper] Converted ${count} cookies from HTTP Header format to Netscape format.`);
  return output;
}

/**
 * Converts a JSON cookie array to the Netscape HTTP Cookie File format.
 * @param {Array} cookiesArray 
 * @returns {string}
 */
function jsonToNetscape(cookiesArray) {
  let output = '# Netscape HTTP Cookie File\n';
  output += '# This file was automatically generated by the bot from cookies.json or YT_COOKIES env var.\n';
  output += '# Do not edit this file directly.\n\n';

  let savedCount = 0;
  const savedNames = [];

  for (const cookie of cookiesArray) {
    if (!cookie.domain || !cookie.name) continue;

    savedCount++;
    savedNames.push(cookie.name);

    const domain = cookie.domain;
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathVal = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
    const name = cookie.name;
    const value = cookie.value || '';

    output += `${domain}\t${flag}\t${pathVal}\t${secure}\t${expiry}\t${name}\t${value}\n`;
  }
  console.log(`ℹ️ [Cookies Helper] Cookies processed: Saved ${savedCount} (${savedNames.join(', ')})`);
  return output;
}

/**
 * Normalizes and cleans raw cookie input string (JSON, Netscape, or Header format)
 */
function parseAnyCookieFormat(rawInput) {
  if (!rawInput || typeof rawInput !== 'string') return null;

  let str = rawInput.trim();
  // Strip outer quotes if any
  if ((str.startsWith('"') && str.endsWith('"')) || (str.startsWith("'") && str.endsWith("'"))) {
    str = str.slice(1, -1).trim();
  }
  if (str.startsWith('YT_COOKIES=')) {
    str = str.substring('YT_COOKIES='.length).trim();
  }
  if (str.startsWith('YOUTUBE_COOKIES=')) {
    str = str.substring('YOUTUBE_COOKIES='.length).trim();
  }

  // Unescape quotes if needed
  str = str.replace(/\\"/g, '"').replace(/\\n/g, '\n');

  // Format 1: JSON Array
  if (str.startsWith('[') || str.startsWith('{')) {
    try {
      let parsed = JSON.parse(str);
      if (Array.isArray(parsed) && Array.isArray(parsed[0])) {
        parsed = parsed.flat();
      }
      if (Array.isArray(parsed)) {
        return { type: 'json', data: parsed };
      }
      if (typeof parsed === 'object' && parsed !== null) {
        return { type: 'json', data: [parsed] };
      }
    } catch (_) {}
  }

  // Format 2: HTTP Header format (key=val; key2=val2)
  if (str.includes(';') && str.includes('=') && !str.startsWith('#')) {
    return { type: 'header', data: str };
  }

  // Format 3: Raw Netscape format (tab or space separated)
  return { type: 'netscape', data: str };
}

/**
 * Loads YouTube cookies, generates valid Netscape cookies.txt, and configures yt-dlp.
 * @returns {Array|undefined} Parsed cookie array if found, otherwise undefined.
 */
function setupCookies() {
  const cookiesTxtPath = path.join(process.cwd(), 'cookies.txt');
  const cookiesJsonPath = path.join(process.cwd(), 'cookies.json');
  const ytDlpBinDir = path.join(process.cwd(), 'bin');
  const confPath = path.join(ytDlpBinDir, 'yt-dlp.conf');

  let rawSource = process.env.YOUTUBE_COOKIES || process.env.YT_COOKIES || null;
  let parsedCookies = null;
  let netscapeText = null;

  // 1. Process Environment Variables if present
  if (rawSource) {
    console.log('🍪 [Cookies Helper] Found cookie environment variable. Parsing format...');
    const result = parseAnyCookieFormat(rawSource);
    if (result) {
      if (result.type === 'json') {
        console.log(`✅ [Cookies Helper] Detected JSON format with ${result.data.length} cookies. Converting to Netscape format...`);
        parsedCookies = result.data;
        netscapeText = jsonToNetscape(parsedCookies);
      } else if (result.type === 'header') {
        console.log('✅ [Cookies Helper] Detected HTTP Cookie Header format. Converting to Netscape format...');
        netscapeText = cookieHeaderToNetscape(result.data);
      } else {
        console.log('✅ [Cookies Helper] Detected Netscape text format. Normalizing tabs...');
        netscapeText = result.data.split('\n').map(line => {
          const trimmed = line.trim();
          if (trimmed.startsWith('#') || trimmed === '') return line;
          return trimmed.split(/\t| {2,}/).join('\t');
        }).join('\n');
      }
    }
  }

  // 2. Fallback to local cookies.json if no env var
  if (!netscapeText && fs.existsSync(cookiesJsonPath)) {
    try {
      const content = fs.readFileSync(cookiesJsonPath, 'utf8');
      const result = parseAnyCookieFormat(content);
      if (result && result.type === 'json') {
        console.log(`✅ [Cookies Helper] Loaded cookies from cookies.json (${result.data.length} cookies).`);
        parsedCookies = result.data;
        netscapeText = jsonToNetscape(parsedCookies);
      }
    } catch (err) {
      console.error('⚠️ [Cookies Helper] Failed to read cookies.json:', err.message);
    }
  }

  // 3. Fallback to existing cookies.txt on disk (Ensure it is NOT JSON)
  if (!netscapeText && fs.existsSync(cookiesTxtPath)) {
    try {
      const diskContent = fs.readFileSync(cookiesTxtPath, 'utf8').trim();
      if (diskContent.startsWith('[') || diskContent.startsWith('{')) {
        console.log('⚠️ [Cookies Helper] Existing cookies.txt is JSON formatted! Fixing to Netscape format...');
        const result = parseAnyCookieFormat(diskContent);
        if (result && result.type === 'json') {
          parsedCookies = result.data;
          netscapeText = jsonToNetscape(parsedCookies);
        }
      } else {
        netscapeText = diskContent;
      }
    } catch (_) {}
  }

  // 4. Write Netscape cookies.txt & configure yt-dlp
  if (netscapeText) {
    try {
      fs.writeFileSync(cookiesTxtPath, netscapeText, 'utf8');
      console.log('✅ [Cookies Helper] Written valid Netscape cookies.txt');

      if (parsedCookies) {
        const health = checkCookiesExpiry(parsedCookies);
        cookiesHealth.checkedAt = new Date().toISOString();
        cookiesHealth.expiredNames = health.expired;
        cookiesHealth.expiringSoonNames = health.expiringSoon;
        cookiesHealth.status = health.ok ? 'ok' : 'expired';
      } else {
        cookiesHealth.status = 'ok';
        cookiesHealth.checkedAt = new Date().toISOString();
      }

      // Configure yt-dlp config
      let confContent = `# Generated by cookies.js\n`;
      confContent += `--extractor-args "youtubetab:skip=authcheck"\n`;
      const normalizedCookiesPath = cookiesTxtPath.replace(/\\/g, '/');
      confContent += `--cookies "${normalizedCookiesPath}"\n`;

      if (fs.existsSync(ytDlpBinDir)) {
        fs.writeFileSync(confPath, confContent, 'utf8');
        console.log(`✅ [Cookies Helper] Configured yt-dlp config at: ${confPath}`);
      }

      return parsedCookies || [{ name: 'YOUTUBE_COOKIES', value: 'netscape' }];
    } catch (err) {
      console.error('⚠️ [Cookies Helper] Failed to write Netscape cookies.txt:', err.message);
    }
  }

  console.log('ℹ️ [Cookies Helper] No cookies configured. Running in unauthenticated mode.');
  cookiesHealth.status = 'missing';
  cookiesHealth.checkedAt = new Date().toISOString();
  return undefined;
}

module.exports = { setupCookies, getCookiesHealth };
